url: "https://www.noesya.coop"
title: "noesya"
baseline: "Coopérative de développeurs"
email: "contact@noesya.coop"
lang: fr

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "metiers"
    values:
      layout: "metier"
  -
    scope:
      path: ""
      type: "members"
    values:
      layout: "member"
collections:
  pages:
    output: true
  metiers:
    output: true
    permalink: /:slug
  members:
    output: true
    permalink: /equipe/:slug

plugins:
  - jekyll-minifier
  - jekyll-sitemap

sass:
  style: compressed
  load_paths:
      - _sass
      - node_modules

jekyll-minifier:
  remove_spaces_inside_tags: true
  remove_multi_spaces: true
  remove_intertag_spaces: false
  remove_comments: true
  compress_css: false
  compress_javascript: true

picture:
  ignore_missing_images: true
