[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "https://noesya.com/*"
  to = "https://www.noesya.coop/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.noesya.com/*"
  to = "https://www.noesya.coop/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://noesya.fr/*"
  to = "https://www.noesya.coop/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.noesya.fr/*"
  to = "https://www.noesya.coop/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.noesya.coop/assets/images/mails/chouette-circle.png"
  to = "https://assets.noesya.coop/images/mails/chouette-circle.png"
  status = 301
  force = true

[[redirects]]
  from = "https://www.noesya.coop/assets/images/mails/facebook.png"
  to = "https://assets.noesya.coop/images/mails/facebook.png"
  status = 301
  force = true


[[redirects]]
  from = "https://www.noesya.coop/assets/images/mails/linkedin.png"
  to = "https://assets.noesya.coop/images/mails/linkedin.png"
  status = 301
  force = true
